### ISSUE TITLE
Force a device to pull latest image from a tag

### ISSUE THREAD

**Issue by AdamVig** [deviceplane/deviceplane#6]
I would like to be able to force a device to pull the latest version of a Docker image when the underlying release has not changed.

For example, I noticed that your [`demo-release`](https://github.com/deviceplane/demo-release/blob/371551a5fa66ae3c9d9fd7bac086b51784b06288/deviceplane.yml) specifies the image by its ID:
```yml
demo-go:
  image: deviceplane/demo-go:614617567844e1b74e45622785719d4b8a728eea
```

I'd like to be able to use an image tag instead:
```yml
demo-go:
  image: deviceplane/demo-go:latest
```

And have some CLI command that allows me to force my devices to pull a newer version of the image specified by the tag `latest`.

**Comment by CyrusRoshan** [comment]
You can! Though you might not want to.

You're probably familiar with the problems with using `:latest` tag, but for others, I wouldn't recommend using `:latest` for the same reasons [Kubernetes discourages it](https://kubernetes.io/docs/concepts/configuration/overview/#container-images) (because it's much harder to pinpoint the image version an service is running on with mutable tags). 

A safer pattern might be to use a [CI pipeline](https://deviceplane.com/docs/deploying/pipelines/) to automatically docker build/push your latest commit on `master`, tagged with the git sha, and then create a deviceplane application release that uses that commit. This can all happen automatically when you push/merge a commit. I think it'll cover what you're trying to do, but also allow you to pinpoint the image version or use [release pinning](https://deviceplane.com/docs/deploying/release-pinning/) to only release the latest version to a certain group of devices.

But back to what you want: currently `:latest` tags are supported in config, and work as other tags do.

For the manual update of a `:latest` image via CLI commands, check out the [docs on command scripting](https://deviceplane.com/docs/operating/command-scripting/#reading-the-output-of-a-command-on-all-devices), and try using a command such as `docker images --format "{{.Repository}}:{{.Tag}}" | grep ':latest' | xargs -L1 docker pull;`, found [here](https://bytefreaks.net/applications/docker/how-to-update-all-pulled-docker-images-that-are-tagged-as-latest).

**Comment by AdamVig** [comment]
Thanks for the reply! This is helpful and, in my opinion, would make sense to add to the documentation under a "Best Practices" or "FAQ" section.

**Comment by CyrusRoshan** [comment]
Good point, I'll create a best practices section in our docs!
